apiVersion: v1
kind: Service
metadata:
  name: bad-service-svc
  namespace: lifecycle-demo
spec:
  type: NodePort
  selector:
    app: bad-service
  ports:
    - protocol: TCP
      port: 8085
      targetPort: grpc
      name: grpc-bad
      nodePort: 30001
---
apiVersion: v1
kind: Service
metadata:
  name: good-service-svc
  namespace: lifecycle-demo
spec:
  type: NodePort
  selector:
    app: good-service
  ports:
    - protocol: TCP
      port: 8085
      targetPort: grpc
      name: grpc-good
      nodePort: 30002
