// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.1
// source: api/demo.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkRequest) Reset() {
	*x = WorkRequest{}
	mi := &file_api_demo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkRequest) ProtoMessage() {}

func (x *WorkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_demo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkRequest.ProtoReflect.Descriptor instead.
func (*WorkRequest) Descriptor() ([]byte, []int) {
	return file_api_demo_proto_rawDescGZIP(), []int{0}
}

func (x *WorkRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type WorkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkResponse) Reset() {
	*x = WorkResponse{}
	mi := &file_api_demo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkResponse) ProtoMessage() {}

func (x *WorkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_demo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkResponse.ProtoReflect.Descriptor instead.
func (*WorkResponse) Descriptor() ([]byte, []int) {
	return file_api_demo_proto_rawDescGZIP(), []int{1}
}

func (x *WorkResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_api_demo_proto protoreflect.FileDescriptor

const file_api_demo_proto_rawDesc = "" +
	"\n" +
	"\x0eapi/demo.proto\x12\x04demo\"!\n" +
	"\vWorkRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\"&\n" +
	"\fWorkResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result2@\n" +
	"\vDemoService\x121\n" +
	"\x06DoWork\x12\x11.demo.WorkRequest\x1a\x12.demo.WorkResponse\"\x00B\x14Z\x12safe-lifecycle/apib\x06proto3"

var (
	file_api_demo_proto_rawDescOnce sync.Once
	file_api_demo_proto_rawDescData []byte
)

func file_api_demo_proto_rawDescGZIP() []byte {
	file_api_demo_proto_rawDescOnce.Do(func() {
		file_api_demo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_demo_proto_rawDesc), len(file_api_demo_proto_rawDesc)))
	})
	return file_api_demo_proto_rawDescData
}

var file_api_demo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_demo_proto_goTypes = []any{
	(*WorkRequest)(nil),  // 0: demo.WorkRequest
	(*WorkResponse)(nil), // 1: demo.WorkResponse
}
var file_api_demo_proto_depIdxs = []int32{
	0, // 0: demo.DemoService.DoWork:input_type -> demo.WorkRequest
	1, // 1: demo.DemoService.DoWork:output_type -> demo.WorkResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_demo_proto_init() }
func file_api_demo_proto_init() {
	if File_api_demo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_demo_proto_rawDesc), len(file_api_demo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_demo_proto_goTypes,
		DependencyIndexes: file_api_demo_proto_depIdxs,
		MessageInfos:      file_api_demo_proto_msgTypes,
	}.Build()
	File_api_demo_proto = out.File
	file_api_demo_proto_goTypes = nil
	file_api_demo_proto_depIdxs = nil
}
